
const testTokenData = [
    { 
      img: 'http://jasperdegens.com/scaffold-eth/assets/complx-forms.mp4',
      name: 'Wall Drawing 692',
      description: "Continuous forms with color ink washes superimposed, reimagined.",
      artistName: "Barak",
      price: 1000,
      ownershipModel: 1,
      balanceRequirement: 1, 
    },
    { 
      img: 'http://jasperdegens.com/scaffold-eth/assets/color-bands.mp4',
      name: 'Wall Drawing 793',
      description: "Irregular Wavy Color Bands, reimagined.",
      artistName: "Barak",
      price: 1000,
      ownershipModel: 1,
      balanceRequirement: 1, 
    },
    { 
      img: 'http://jasperdegens.com/scaffold-eth/assets/displacement-color.mp4',
      name: 'Vertex Displacement 1',
      description: "Playing around with vertex displacement in TouchDesigner.",
      artistName: "Barak",
      price: 1000,
      ownershipModel: 1,
      balanceRequirement: 2, 
    },
    { 
      img: 'http://jasperdegens.com/scaffold-eth/assets/displacement-gold.mp4',
      name: 'Vertex Displacement 2',
      description: "Playing around with vertex displacement in TouchDesigner.",
      artistName: "Barak",
      price: 1000,
      ownershipModel: 0,
      balanceRequirement: 5, 
    },
    { 
      img: 'http://jasperdegens.com/scaffold-eth/assets/portrait.jpg',
      name: 'Dithered Portrait',
      description: "Dithered portrait made with Processing and Axidraw using the Floyd-Steinberg algorithm.",
      artistName: "Barak",
      price: 1000,
      ownershipModel: 1,
      balanceRequirement: 3, 
    },
    { 
      img: 'http://jasperdegens.com/scaffold-eth/assets/land.mp4',
      name: 'Land Unknown',
      description: "Painting a land unknown.",
      artistName: "Barak",
      price: 1000,
      ownershipModel: 0,
      balanceRequirement: 10, 
    },
    { 
      img: 'http://jasperdegens.com/scaffold-eth/assets/zen.mp4',
      name: 'Zen',
      description: "Discover zen.",
      artistName: "Barak",
      price: 1000,
      ownershipModel: 1,
      balanceRequirement: 5, 
    },
    { 
      img: 'http://jasperdegens.com/scaffold-eth/assets/internal-state.mp4',
      name: 'Internal State',
      description: "A turbulent internal state.",
      artistName: "Barak",
      price: 1000,
      ownershipModel: 1,
      balanceRequirement: 1, 
    },
    { 
      img: 'http://jasperdegens.com/scaffold-eth/assets/drift.mp4',
      name: 'Drift',
      description: "Experiments with noise and patterns.",
      artistName: "Barak",
      price: 1000,
      ownershipModel: 0,
      balanceRequirement: 20, 
    },
    { 
      img: 'http://jasperdegens.com/scaffold-eth/assets/shoreditch.mp4',
      name: 'Shoreditch HDRI',
      description: "Algorithmic design practive, virtually in London.",
      artistName: "Barak",
      price: 1000,
      ownershipModel: 1,
      balanceRequirement: 1, 
    },
    
];


module.exports = testTokenData;